try {
  // This block is used to handle exceptions
  int num1 = 5;
  int? num2; // The ? denotes a nullable value
  int result;

  result = num1 ~/ num2!; // Using the ! to avoid null error

  if (result.isNaN) {
    // Checks if the result is not a number
    throw FormatException('Division by zero is not allowed');
  } else {
    // If result is a number, print it
    print('Result: $result');
  }
} on IntegerDivisionByZeroException {
  // Catches the exception if num2 is 0
  print('Cannot divide by zero');
} on FormatException catch (e) {
  // Catches the FormatException and prints the error message
  print(e.message);
} catch (e) {
  // Catches any other type of exception
  print('Unknown exception: $e');
} finally {
  // This block always gets executed regardless of exceptions
  print('Calculation complete');
}