defmodule Math do
  # This function returns the sum of two integers
  def add(a, b) do
    a + b
  end

  # This function returns the result of subtracting two integers
  def subtract(a, b) do
    a - b
  end

  # This function returns the result of multiplying two integers
  def multiply(a, b) do
    a * b
  end

  # This function returns the result of dividing two integers
  def divide(a, b) do
    # Check if the denominator is 0, if it is, raise an exception
    if b == 0 do
      raise "Denominator cannot be 0"
    else
      a / b
    end
  end
end

# Creating a new instance of the Math module
math = Math.new()

# Calling the add function with the values 10 and 5
result = math.add(10, 5)

# Printing the result
IO.puts("The result is: #{result}")

# Calling the subtract function with the values 10 and 5
result = math.subtract(10, 5)

# Printing the result
IO.puts("The result is: #{result}")

# Calling the multiply function with the values 10 and 5
result = math.multiply(10, 5)

# Printing the result
IO.puts("The result is: #{result}")

# Calling the divide function with the values 10 and 5
result = math.divide(10, 5)

# Printing the result
IO.puts("The result is: #{result}")

# Calling the divide function with the values 10 and 0
result = math.divide(10, 0) # This should raise an exception

# Printing the result
IO.puts("The result is: #{result}") # This line will not be executed due to the exception