import std.stdio; // Import module for standard input/output functions
import std.exception; // Import module for handling exceptions

void main()
{
    int[] numbers = [1, 2, 3, 4, 5]; // Create an array of integers

    foreach (num; numbers) // Loop through the array using "foreach" loop
    {
        try // Use "try" block to catch any exceptions
        {
            if (num == 5) // Check if current number is 5
                throw new Exception("Oops! Number 5 found!"); // Throw an exception if number is 5
        }
        catch(Exception e) // Catch the exception
        {
            writeln(e.msg); // Print the message of the exception using standard output function
        }
    }
}